# Generated by Django 6.0.4 on 2026-04-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('age', models.IntegerField()),
                ('reels_watch_time_hours', models.FloatField()),
                ('daily_screen_time_hours', models.FloatField()),
                ('sleep_hours', models.FloatField()),
                ('attention_span_score', models.IntegerField()),
                ('focus_level', models.IntegerField()),
                ('task_completion_rate', models.FloatField()),
                ('stress_level', models.CharField(max_length=10)),
                ('platform', models.CharField(max_length=50)),
            ],
        ),
    ]
